### ISSUE TITLE
feature:

### ISSUE THREAD

**Issue by fvalette** [camelot-os/barbican#14]
### What is proposed ?

Define a dedicated configuration file for SDK using a toml file format.
This toml shall describe: 

- the compiler needed (c/ada/rust), their resp. download source, version, targets.
- sentry kernel sources and configuration file
- system library sources and configuration file (e.g. merlin, shield)

**Comment by PThierry** [comment]
In SDK production mode, it would be great to support such a following content:
```toml
[library]
scm.git.uri = 'https://github.com/libecc/libecc.git'
scm.git.revision = 'v1.2.3'
arglist = [ '-Dfoo', '-Dconfig=${project_root}/configs/libecc/libecc.config' ] # note: no kconfig in libecc, but usefull for LVGL config
depends = 'shield' # for libs that depend on another SDK entry(ies)
provides = [ 'libecc.a', 'ec_utils' ]
````

Note: C libs should allow deployment of both sources & prebuilt (including .pc), while Rust libs should deploy sources in the Cargo SDK repository alongside sentry-uapi

This means that, by now, we supports meson & cargo based components only.
